travis:
  secure:
    BINSTAR_TOKEN: M8s5GeDZ8oPyHwYfXj1OtmSvOWcG/Qk4xoSvYunPy0i1jc0er791XPxGErWQ9+6/0TRzyYZctO2hNlkY89NciYs6sCDdM1cahnmgV+Axgbm6YAzFUP9qfc7y11rFYa/p4tqFCHdP6qWcgKvx/JiEQWAJvbFM28fjNqqDGolSEUv2a8RThv1aeuY1Lw3Sj4BYmPjY9pwQaIFUJalaPuIz1wSRMEJeM1ys9P2rivzSjrOxvOZwuqt3UoPZydxDsc2RKlKyVI6DWty531vMOtOFxEgrKc2nSFj0H2qcZHvJ45xa5wL6OxszUiEk0da1qa8PXSF4WvBX/IQ1Ldt2jMX83u5qgtYD/FK/3A2NITQYsfKwoSOb4EG6FIJYbn872CxrQSobqgGKVVL1PeYrLpmXQTMfBYzfGRqHMJ33CVKqqsn0OdfIjtYcuMU4pvpniE1u1VmWOKc53FM0McDBIEoDO6Yq9N7cxB93QwzJQq8jN06ZpWW4XiYvUI6j5G3nH7C0/W2dQeOnCkVedjWodcrDQ4QIZv1i2SJnuYNGGsbWhTeVrp3pnea3JLGHrhpRdfe99xNQsox5UxGyqUHudUr3vUxEwQfV5yFC8JmaAyiJUqikOUU2F7W+rtdr8GNvaAyNnP+V3yDPM2CacO9+Ue5aWnLXhcpeoTSlMCbElSdzmLM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
